---
- name: Converge
  hosts: all
  gather_facts: True
  roles:
    - role: cambid.intersystems_cache
  vars:
    - hs_distribution_version: 2017.2.2.865.3
    - hs_cache_usr: root
    - hs_cache_usr_sys: root
    - hs_cache_group: root
    - ISC_PACKAGE_UNICODE: Y
    - ISC_BINARY_TYPE: unicode
    - SECURITY_LEVEL: None
