---
dist: xenial
sudo: required
language: python

services:
  - docker

before_install:
  - wget -P files/iris --no-verbose --http-user=${username} --http-password=${password} https://download.faderweb.de/IRIS-2019.1.0.510.0-lnxubuntux64.tar.gzhttps://download.faderweb.de/IRIS-2019.1.0.510.0-lnxrhx64.tar.gz
  - touch files/iris/iris.key

install:
  - sudo -H pip install --upgrade pip
  - sudo -H pip install molecule docker-py ansible

script:
  - molecule --version
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
