dist: xenial
sudo: required
language: python

services:
  - docker

env:
  - distribution: centos
    distribution_name: rh
    version: 7
  - distribution: cambid/ubuntu-python
    distribution_name: ubuntu
    version: latest

before_install:
  - wget -P files/iris --no-verbose --http-user=${username} --http-password=${password} https://download.faderweb.de/IRIS-2019.1.0.510.0-lnx${distribution_name}x64.tar.gz
  - touch files/iris/iris.key
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker run --name ${distribution/cambid\//}_${version} -d ${distribution}:${version} sleep infinity'

install:
  - sudo -H pip install --upgrade pip
  - sudo -H pip install docker-py
  - sudo -H pip install ansible

script:
  - ANSIBLE_ROLES_PATH=.. ansible-playbook --syntax-check tests/iris.yaml
  - ANSIBLE_ROLES_PATH=.. ansible-playbook -l ${distribution/cambid\//}_${version} -i tests/inventory tests/iris.yaml
