sudo: required

services:
  - docker

env:
  - distribution: centos
    version: 7
  - distribution: cambid/ubuntu-python
    version: latest

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker run --name ${distribution/cambid\//}_${version} -d ${distribution}:${version} sleep infinity'

install:
  - sudo pip upgrade
  - sudo pip install docker-py
  - sudo apt-get install ansible

script:
  - ANSIBLE_ROLES_PATH=../.. ansible-playbook --syntax-check tests/iris.yaml
  - ANSIBLE_ROLES_PATH=../.. ansible-playbook -i tests/inventory tests/iris.yaml
