---
- name: "include os-specific variables"
  include_vars: os-{{ ansible_os_family }}.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'RedHat'

- include_tasks: setup-{{ ansible_os_family }}.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'RedHat'

- include_tasks: configure-cache.yml
