---
- include_vars: os-{{ ansible_os_family  }}.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'RedHat'

- include: setup-{{ ansible_os_family }}.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'RedHat'

- include: configure-cache.yml
