---
- name: Restart Cache
  ansible.builtin.command: ccontrol stop "{{ ISC_PACKAGE_INSTANCENAME }}" restart quietly
  listen: "restart database"
  when: hs_distribution_file is not search("IRIS")
  changed_when: true

- name: Restart IRIS
  ansible.builtin.command: iris stop "{{ ISC_PACKAGE_INSTANCENAME }}" restart quietly
  listen: "restart database"
  when: hs_distribution_file is search("IRIS")
  changed_when: true

- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
