---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: centos_7
    image: centos:7
  - name: ubuntu_bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
